version: '3.0'

services:
  php:
    container_name: ${PHP_CONTAINER_NAME}
    build:
      context: .docker/php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHPREDIS_VERSION=${PHPREDIS_VERSION}
        - INSTALL_REDIS=${INSTALL_REDIS}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    restart: always
    ports:
      - "9005:9000"
    volumes:
      - ./:/www
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - "6679:6379"
