version: '3.7'

services:
  php:
    container_name: ${PHP_CONTAINER_NAME}
    build:
      context: .docker/php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - SWOOLE_VERSION=${SWOOLE_VERSION}
        - PHPREDIS_VERSION=${PHPREDIS_VERSION}
        - XLSWRITER_VERSION=${XLSWRITER_VERSION}
        - INSTALL_REDIS=${INSTALL_REDIS}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - INSTALL_XLSWRITER=${INSTALL_XLSWRITER}
        - INSTALL_SWOOLE=${INSTALL_SWOOLE}
    restart: always
    ports:
      - "${PHP_PORT}:9000"
    volumes:
      - ./:/var/www/html

  web:
    container_name: ${NGINX_CONTAINER_NAME}
    image: nginx:${NGINX_VERSION}
    restart: always
    ports:
      - "${WEB_PORT}:80"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d

  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
