version: '3.7'

services:
    php:
        container_name: php
        build: .docker/php
        restart: always
        ports:
          - "${PHP_PORT}:9000"
        volumes:
          - ./:/var/www/html

    web:
        container_name: web
        image: nginx:${NGINX_VERSION}
        restart: always
        ports:
          - "${WEB_PORT}:80"
        environment:
          TZ: "${TIME_ZONE}"
        volumes:
          - ./:/var/www/html
          - ./.docker/nginx/conf.d:/etc/nginx/conf.d

    redis:
        container_name: redis
        image: redis:${REDIS_VERSION}
        restart: always
        ports:
          - "${REDIS_PORT}:6379"
