name: Docker Compose Actions Workflow

on: push
jobs:
  test:
    runs-on: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy the environment
        run: cp .env.example .env
      - name: Build the stack
        run: docker-compose up -d
      - name: Exec the docker
        run: docker exec -it web php sh
